// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7xIUzYF8yYrXty5UJkm-ANRW7q9dL15M',
    appId: '1:302591567499:web:34d218398f6440f3c8568e',
    messagingSenderId: '302591567499',
    projectId: 'fir-authproject-8d348',
    authDomain: 'fir-authproject-8d348.firebaseapp.com',
    storageBucket: 'fir-authproject-8d348.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEwFo0UgSV7Kmo6sTNb-zkGPtlXu18v0',
    appId: '1:302591567499:android:31d7bbae70e21bf4c8568e',
    messagingSenderId: '302591567499',
    projectId: 'fir-authproject-8d348',
    storageBucket: 'fir-authproject-8d348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Up6sYjr_Y-3vLTVFeWnymDtSFXLpd7U',
    appId: '1:302591567499:ios:7cdcae93d3a9c497c8568e',
    messagingSenderId: '302591567499',
    projectId: 'fir-authproject-8d348',
    storageBucket: 'fir-authproject-8d348.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Up6sYjr_Y-3vLTVFeWnymDtSFXLpd7U',
    appId: '1:302591567499:ios:7cdcae93d3a9c497c8568e',
    messagingSenderId: '302591567499',
    projectId: 'fir-authproject-8d348',
    storageBucket: 'fir-authproject-8d348.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7xIUzYF8yYrXty5UJkm-ANRW7q9dL15M',
    appId: '1:302591567499:web:8c77584d679dc7d0c8568e',
    messagingSenderId: '302591567499',
    projectId: 'fir-authproject-8d348',
    authDomain: 'fir-authproject-8d348.firebaseapp.com',
    storageBucket: 'fir-authproject-8d348.firebasestorage.app',
  );
}
